### ISSUE TITLE
bug fix.

### ISSUE THREAD

**Issue by YaoXinZhi** [SouthGreenPlatform/PyRice#4]
When running the demo, the code reported this error: 
`bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml.`
I modified the source code file, line 67 in multi_query.py
`database_description = BeautifulSoup(self.database_file, "xml").find_all("database", dbname=db.lower())`
Change the ‘xml’ to ‘lxml’ to fix this error, it may be a compatibility error that needs to be adjusted.

**Comment by hongquando** [comment]
Sorry for the late response. To fix your problems:

1. I think you can install lmxl follow the command: **pip install lxml**
For more details, you can visit [here](https://stackoverflow.com/questions/24398302/bs4-featurenotfound-couldnt-find-a-tree-builder-with-the-features-you-requeste)

2. You should keep "xml" in command:
```database_description = BeautifulSoup(self.database_file, "xml").find_all("database", dbname=db.lower())```
P/s: When I run with "lxml" in command above, I have the same problems in the file that you send us.

After you do 2 steps, I think you can successfully run the package

**Comment by hongquando** [comment]
> When running the demo, the code reported this error:
> `bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml.`
> I modified the source code file, line 67 in multi_query.py
> `database_description = BeautifulSoup(self.database_file, "xml").find_all("database", dbname=db.lower())`
> Change the ‘xml’ to ‘lxml’ to fix this error, it may be a compatibility error that needs to be adjusted.

**Comment by hongquando** [comment]
> When running the demo, the code reported this error:
> `bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml.`
> I modified the source code file, line 67 in multi_query.py
> `database_description = BeautifulSoup(self.database_file, "xml").find_all("database", dbname=db.lower())`
> Change the ‘xml’ to ‘lxml’ to fix this error, it may be a compatibility error that needs to be adjusted.

Sorry for the late response. To fix your problems:

1. I think you can install lmxl follow the command: **pip install lxml**
For more details, you can visit [here](https://stackoverflow.com/questions/24398302/bs4-featurenotfound-couldnt-find-a-tree-builder-with-the-features-you-requeste)

2. You should keep "xml" in command:
```database_description = BeautifulSoup(self.database_file, "xml").find_all("database", dbname=db.lower())```
P/s: When I run with "lxml" in command above, I have the same problems in the file that you send us.

After you do 2 steps, I think you can successfully run the package.
